version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    restart: always
    command: >
      sh -c "python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            python create_superuser.py &&
            gunicorn setup.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    restart: always
    command: celery -A setup worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
