# Generated by Django 4.2.11 on 2025-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotivePartsManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['manufacturer', 'name', 'year']},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='partcarmodel',
            options={'ordering': ['part', 'car_model']},
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
